'use client';

import Head from 'next/head';

import { useState } from 'react';
import { addNumber } from '@/utils/calculator';
import styles from './calculator.module.scss';

export default function Calculator() {
  const [num1, setNum1] = useState('0');
  const [num2, setNum2] = useState('0');
  const [result, setResult] = useState(0);
  const add = () => {
    const addResult = addNumber(num1, num2);
    setResult(addResult);
  };
  const subtract = () => {
    setResult(parseInt(num1, 10) - parseInt(num2, 10));
  };
  const multiply = () => {
    setResult(parseInt(num1, 10) * parseInt(num2, 10));
  };
  const divide = () => {
    setResult(parseInt(num1, 10) / parseInt(num2, 10));
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.result} data-testid="result">
        {result}
      </div>
      <input
        type="number"
        className={styles.input}
        data-testid="num1"
        value={num1}
        onChange={(e) => setNum1(e.target.value)}
      />
      <input
        type="number"
        className={styles.input}
        data-testid="num2"
        value={num2}
        onChange={(e) => setNum2(e.target.value)}
      />
      <button type="button" onClick={add} className={styles.button} data-testid="add">
        Add
      </button>
      <button type="button" onClick={subtract} className={styles.button} data-testid="subtract">
        Subtract
      </button>
      <button type="button" onClick={multiply} className={styles.button} data-testid="multiply">
        Multiply
      </button>
      <button type="button" onClick={divide} className={styles.button} data-testid="divide">
        Divide
      </button>
    </div>
  );
}
